name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: kasfy/kasfy.js.org
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm install && echo "kasfy.js.org" >> src/.vuepress/public/CNAME &&   npm run build
        BUILD_DIR: src/.vuepress/dist/
